### ISSUE TITLE
Question about authorship // JOSE REVIEW

### ISSUE THREAD

**Issue by bjrubinstein** [hydroframe/SandTank#61]
@lecondon I'm reviewing your submission for JOSE and I have a question about the author's list. I was looking through the commits and it looks like @callachennault has made significant contributions to the code but is not listed as an author and Lisa Gallagher is listed as an author but doesn't have any public contributions to the repo. Can you please clarify this for me?

**Comment by reedmaxwell** [comment]
Hi @bjrubinstein thanks for reviewing this manuscript for JOSE!  I'm answering for @lecondon who is out on maternity leave.  I'm not sure that GitHub reflects her email OoO.  The paper was written and submitted more than two years ago and this was before @callachennault started on the project.  My guess is that it also has my old affiliation, I changed institutions a bit more than two years ago as well.  I'm sorry about the confusion, I had completely forgotten that we submitted this manuscript and had more or less given up on the journal.  I'm delighted that review might actually occur and we are happy to add @callachennault as an author.  (Dr.) Lisa Gallagher is an education researcher and specialist and an important contributor to this work.  She has contributed substantially to the design of the software package and I suspect that most productive educational software packages have non-research software engineers who contribute to the project.  Hope this helps clarify, thanks much.

**Comment by djlampert** [comment]
So, it seems like the affiliations for the article need to be updated, then we can move forward with the review for JOSE?

**Comment by bjrubinstein** [comment]
@reedmaxwell Thanks for the clarifications. I'm not sure if they expect things to be updated or if it's acceptable that they were accurate at the time the paper was submitted.

I left a question for the editor in the review issue: https://github.com/openjournals/jose-reviews/issues/179#issuecomment-1196105835 I'll update when we hear back.

**Comment by lecondon** [comment]
I have added @callachennault  to the author list
