### ISSUE TITLE
Question about release version // JOSE REVIEW

### ISSUE THREAD

**Issue by djlampert** [hydroframe/SandTank#62]
Hello, I am also reviewing this article/repo for the Journal of Open Source Education (JOSE) along with @bjrubinstein. The release version listed in the manuscript is 1.0.6, but the release for the GitHub repository is 1.1.1. Please update. Thanks.

**Comment by lecondon** [comment]
Thanks for the review! We would be happy to update this however I'm not sure where to go to update that since I think its actually in the JOSE system. Can you point out where you want this updated?

**Comment by lecondon** [comment]
This has been updated by the editor.
