### ISSUE TITLE
Fix DOI for OseiK:2014 in BibTeX file // JOSE REVIEW

### ISSUE THREAD

**Issue by bjrubinstein** [hydroframe/SandTank#63]
@reedmaxwell The DOI field for Improved numerical solvers for implicit coupling of subsurface and overland flow by Osei-Kuffuor, D. and Maxwell, R. M. and Woodward, C. S. includes a "https://doi.org/" prefix.

Current:
`DOI = {https://doi.org/10.1016/j.advwatres.2014.09.006},`

Should be:
`DOI = {10.1016/j.advwatres.2014.09.006},`

**Comment by lecondon** [comment]
Thanks for point that out. This has been corrected and I also fixed another reference that had the same issue.
