### ISSUE TITLE
Node.js version dependency documentation // JOSE REVIEW

### ISSUE THREAD

**Issue by bjrubinstein** [hydroframe/SandTank#64]
@reedmaxwell The instructions for building the web client in the readme or running the development web server in the Web Application page of the documentation have the following commands respectively:

```
cd ./client
npm install
npm run build
```

```
cd client
npm run serve
```

These fail with the a ERR_OSSL_EVP_UNSUPPORTED on Node version 18 or higher. Last time the documentation was updated version 18 hadn't been released but now that the dependency exists could you please update the documentation to reflected it?

**Comment by reedmaxwell** [comment]
thanks, tagging @jourdain

**Comment by jourdain** [comment]
A quick google search lead me to [`export NODE_OPTIONS=--openssl-legacy-provider`](https://stackoverflow.com/questions/69394632/webpack-build-failing-with-err-ossl-evp-unsupported). Not sure if that fix it or not.

**Comment by lecondon** [comment]
I added a note to the readme that version 17 or lower is required. I think that should address this issue.

**Comment by bjrubinstein** [comment]
Thanks @lecondon . That looks good to me.
